### ISSUE TITLE
ToPEM 관련 질문 드립니다.

### ISSUE THREAD

**Issue by owljoa** [it-chain/heimdall#10]
각 Key별로 ToPEM()으로 

RSA의 경우
--rsa.go--

func (key *RsaPrivateKey) ToPEM() ([]byte,error) {
	keyData := x509.MarshalPKCS1PrivateKey(key.priv)

	return pem.EncodeToMemory(
		&pem.Block{
			Type: "RSA PRIVATE KEY",
			Bytes: keyData,
		},
	), nil
}

이런식으로 구현 하셨는데, 

키 유틸에서도 같은 기능이 구현이 되어 있네요.
--KeyUtils.go--
func PublicKeyToPEM(pub Key) ([]byte, error)
func PrivateKeyToPEM(pri Key) ([]byte, error)

이렇게 같은 기능을 만들어두신 특별한 이유가 있나요??

**Comment by junbeomlee** [comment]
2가지 이유가 있는데요 일단 byte로 변환해서 파일 시스템에 저장하기 위함!! 이고
나머지는 pubkey를 다른 peer에게 전송해야되는데 그때 byte로 변환해서 전송합니다!!

**Comment by junbeomlee** [comment]
아아 keyUtils.go는 예전 파일이라 아마 지워질꺼 같습니다.

**Comment by junbeomlee** [comment]
리팩과정에서 ToPEM을 keyUtils.go에서 rsa ecdsa고 옮겼습니다.

**Comment by junbeomlee** [comment]
그부분은 Key에 들어갈수는 없을 것 같고 복구하는 로직은 KeyManager에 들어있습니다.

**Comment by junbeomlee** [comment]
지금 라이브러리 분할 과정에 있습니다. packaging 브런치에서 @yojkim 가 작업중입니다. 도와주셔도 되여 ㅋㅋ

**Comment by owljoa** [comment]
아하하; 여차저차 문법 검색하면서 전체적인 그림은 따라온것 같은데, 어떤 그림을 그리고 계시는지 몰라서요.. 그냥 이슈에 제안을 드려도 되는건가요?

**Comment by junbeomlee** [comment]
넵 당연하죠!!

**Comment by owljoa** [comment]
아아 ㅋㅋ 넵 :) 그럼 일단 packaging 브랜치도 한번 둘러보겠습니다~

**Comment by yojkim** [comment]
@owljoa  현재는 원래 있던 `auth` 패키지를 3개 정도로 분할하고 있는데요 

`auth` : 서명하고 검증만을 담당
`hash` : 서명 전에 넘길 데이터를 해싱처리하는 것을 담당
`key` : key 생성과 저장 및 로드를 담당 

요정도로 생각중입니다.

**Comment by owljoa** [comment]
@yojkim 오... 넵! 참고하겠습니다.
