### ISSUE TITLE
개인적으로 Key interface를  Key와  PRIKEY , PUBKEY3개로 구현해서

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/heimdall#11]
type key interface {

}

type priKey interface{
   key 
}

type pubKey interface{
   key 
}

로 해주는게 좋을것 같아요. 만약에 prikey에서  pubkey를 얻는다던지 하는 operation들 같은 경우에는 같은 Key interface로는 처리할 수 없기때문에 공통 interface와 개별 interface 를 나눠서 구현해주는것이 더 좋은 방법일것같습니다

**Comment by yojkim** [comment]
네

**Comment by junbeomlee** [comment]
완료 된듯? 됬으면 Close해주세요

**Comment by yojkim** [comment]
근데 아직 인터페이스만 만들고 적용은 안했는데 괜춘한가여? 된건가??

**Comment by junbeomlee** [comment]
아그래?!!

저번에 나누는거 같아서 한줄알고 ㅋㅋㅋ 아직 못봄 코드를

2018년 3월 28일 (수) 오후 5:29, Yong Jae Kim <notifications@github.com>님이 작성:

**Comment by junbeomlee** [comment]
키 Load 할때 pri, pub Key가 아니라 pri PriKey, pub PubKey로만 처리해주면 대충 될듯?!

**Comment by yojkim** [comment]
넵

**Comment by yojkim** [comment]
@junbeomlee 이거는 형이 해주신거죠??

**Comment by junbeomlee** [comment]
얍

2018년 4월 1일 (일) 오후 12:30, Yong Jae Kim <notifications@github.com>님이 작성:
