### ISSUE TITLE
authImpl.go에 NewAuth function에 대한 질문입니다!

### ISSUE THREAD

**Issue by owljoa** [it-chain/heimdall#15]
signers := make(map[reflect.Type]signer)
signers[reflect.TypeOf(&key.RSAPrivateKey{})] = &RSASigner{}
signers[reflect.TypeOf(&key.ECDSAPrivateKey{})] = &ECDSASigner{}

디버그를 하다보니 NewAuth function내에 있는 위 코드가 걸려서요.
타입에 따라 다른 종류의 signer를 저장하려는 의도이신건지..
아니면 미리 두 타입 모두의 signer를 초기화하시는 것을 의도하신건지..
궁금합니다!

![20180328_125013](https://user-images.githubusercontent.com/32866399/38007875-9ee3865e-3286-11e8-8348-69821b5d9003.png)

이유는 위 이미지와 같이 만들어두신 RSA sample로 디버그할때 위 코드를 지나가도 signers 변수에 RSA Signer만 초기화되는것으로 보여서요.

**Comment by yojkim** [comment]
후자가 맞을 듯 합니다. 두 타입의 `Signer`를 모두 초기화해서 `Sign()`시에 `key` 생성 알고리즘에 따라서 프로세스가 진행될 수 있도록 구성한 것입니다. `Verifier`도 동일합니다.

**Comment by owljoa** [comment]
아하! 그런데 디버그 진행했을때는 올려드린 이미지처럼
signers[reflect.TypeOf(&key.ECDSAPrivateKey{})] = &ECDSASigner{}
이 라인도 동작은 하는데 결과로 메모리를 잡지 않아서 signers의 RSASigner으로 보이고..

그리고 signers에서만 둘의 순서를 바꿔보니 아래 이미지와 같이 signers는 ECDSASigner, verifiers에는 RSAVerifier만 메모리에 할당되는 것으로 보여서 확인이 필요할 것 같습니다..!

![debug1](https://user-images.githubusercontent.com/32866399/38012611-14948b4e-329d-11e8-8ecb-0c92c4573319.png)

**Comment by yojkim** [comment]
동작은 하는데 메모리에 안잡힌다는게 뭔가 좀 이상하긴한데 확인이 필요할 것 같긴하네요.

**Comment by yojkim** [comment]
@owljoa 
제가 새로 작성된 `heimdall-rsa-sample.go`를 디버그해보면서 확인해보았는데요.
`RSASigner`, `ECDSASigner` 모두 정상적으로 메모리에 등록되는걸로 모이는데 VS Code에서 보여질때 뭔가 문제가 있는것 아닐까요?

![2018-03-28 4 16 29](https://user-images.githubusercontent.com/2631975/38014520-048df01c-32a4-11e8-9358-c961cbf052a8.png)

**Comment by owljoa** [comment]
앗 이런.. 그런것 같네요..!
역시 인텔리제이로 옮겨야하는건가요 하하 :(

이슈 종료하겠습니다!
