### ISSUE TITLE
테스트 코드 작성

### ISSUE THREAD

**Issue by yojkim** [it-chain/heimdall#21]
구현된 파일들에대해서 테스트를 진행해야함

**Comment by junbeomlee** [comment]
테스트 코드 작성 원하시나요?

**Comment by owljoa** [comment]
넵!

**Comment by yojkim** [comment]
ㅋㅋㅋ앗 제가 테스트 파일들 만든거 곧 푸쉬하겟슴당

**Comment by yojkim** [comment]
`master` 브랜치에 테스트 파일들 생성한거 머지했습니다. `testcode` 브랜치에서 테스트코드 작성할 생각입니당

**Comment by yojkim** [comment]
@owljoa 혹시 key쪽 test 작성 곧 될까요? 아니라면 그쪽 제외하고 태그 달까해서욥

**Comment by owljoa** [comment]
@yojkim 음.. 오늘내로 해볼게요!
