### ISSUE TITLE
Pem에서 키를 복구하는 로직

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/heimdall#24]
Pem에서 키를 복구하는 로직이 따로 있어야 할 것 같습니당.

[]byte형태로 pem을 받으면 파일형태가 아니라 []byte만 있음. 이럴때 복구해야되는데 복구하는 함수가 type, []byte를 받아서 해당하는 Key로 반환해주는함수가 있으면 좋겠습니당. 그래야 peer끼리 key교환할 수 있습니다. 도와주세요!!

**Comment by yojkim** [comment]
전 이제 auth에서 손을 ....

**Comment by owljoa** [comment]
넵!

**Comment by owljoa** [comment]
에구 잘못 눌렀네요 ㅋㅋ; 
저 pem -> 키 복구는 제가 한번 해보겠슴다 :)

**Comment by junbeomlee** [comment]
ㅋㅋㅋㅋ 그럼 내가 저부분 제외하고 나머지 조금 수정해야지~
@yojkim 이제 어디를 도전?!!

**Comment by yojkim** [comment]
ㅋㅋㅋㅋ일단 테스트코드점ㅋㅋㅋ 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by junbeomlee** [comment]
@owljoa  
어떤 알고리즘인지, 어떤 타입인지, []byte이렇게 3개를 받으면 해당 key로 바꿔주는 함수가 필요할 것 같습니다. 이미 부분부분은 다 구현되어있기 때문에 기존코드를 참조하시면 금방 만드실수 있을 것 같습니다!

**Comment by owljoa** [comment]
아아 넵 ! 오늘은 안될것 같고.. 내일 한번 만들어볼게요!

**Comment by owljoa** [comment]
@junbeomlee @yojkim 다시 생각해보니 통신상에 private key가 직접 돌아다닐 일은 없을테니 private key에 대한 byteToKey 기능은 지우는것이 좋을것 같은데 어떠세요??

**Comment by junbeomlee** [comment]
그렇지만 이왕 만들었고 사용하는것은 사용자 마음이니 그냥 두는것이 좋을 것 같습니다!

**Comment by yojkim** [comment]
요거는 완료된건가요?!

**Comment by yojkim** [comment]
@junbeomlee ?.?

**Comment by owljoa** [comment]
이 기능...은 일단 완료된것 같은데요?
저도 @junbeomlee 님 말씀대로 선택지로 두는것이 괜찮을것 같습니다 :)

**Comment by junbeomlee** [comment]
Close해주세요!
