### ISSUE TITLE
Verify에서는 pub키를 넣는데 sign에서는 pri안넣으니까 이상함!!!

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/heimdall#3]

**Comment by yojkim** [comment]
원래는 pri키를 넣었었는데 그때 중복검사 힘들어서 그냥 키 생성하는 걸로 하라고하셔가지고 그렇게한거였는데 다시 바꿀까요

**Comment by junbeomlee** [comment]
이제는 라이브러리라 최대한 외부에서 받는게 좋을듯! ㅇㅇㅇㅇㅇ

**Comment by junbeomlee** [comment]
KeyManager도 이제는 별로인거같고 pri, pub은 알아서 저장하는거고 generator정도만 해주는게 제일 좋을 거 같긴함

**Comment by yojkim** [comment]
@junbeomlee 그러면 key 관련해서 해야할게
1. `Sign()`에서 private key도 같이 입력받는 것
2. `KeyManager`에서 키 생성만 담당하고 저장은 알아서 하도록?! (아니면 옵션으로 제공할까요?)

**Comment by junbeomlee** [comment]
그 아니아니 그 keymanager는 갠춘한대 crpyto에서 pri, pub을 가지고있는거 말한거임 ㅎㅎ..

**Comment by junbeomlee** [comment]
keymanager는 store, load의 역할이라 좋음

**Comment by yojkim** [comment]
결론적으로는 1번을 하면되는거죱?

**Comment by yojkim** [comment]
옙

**Comment by junbeomlee** [comment]
```
	priKey			Key
	pubKey			Key

	keyManager		keyManager
	signers 		map[reflect.Type]signer
	verifiers 		map[reflect.Type]verifier
	keyGenerators 	map[reflect.Type]keyGenerator
```
아래 4개는 각각 존재해도 괜찮을듯 함
signer, verifier, keyGenerators의 초반 세팅은 어디서 할지 고민해봐야할듯
