### ISSUE TITLE
key store path

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/heimdall#30]
지금은 ./keyRepository이렇게 되는데 ./heimdall이런게 더 멋지지 않을까여 다들 어캐 생각하시나요?

**Comment by yojkim** [comment]
멋지긴한데 좀 알아보기 힘들지 않을까욧? 상관없나

**Comment by owljoa** [comment]
디폴트 디렉토리 말씀하시는거라면 알아보기 힘들어도 문제되지 않을것같아요! :)
