### ISSUE TITLE
pubkey -> byte, byte-> pubkey

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/heimdall#4]
이거는 꼭 해야함!!

**Comment by junbeomlee** [comment]
ipfs에서 

```
func UnmarshalRsaPublicKey(b []byte) (PubKey, error) {
	pub, err := x509.ParsePKIXPublicKey(b)
	if err != nil {
		return nil, err
	}
	pk, ok := pub.(*rsa.PublicKey)
	if !ok {
		return nil, errors.New("Not actually an rsa public key.")
	}
	return &RsaPublicKey{pk}, nil
}

func MarshalRsaPublicKey(k *RsaPublicKey) ([]byte, error) {
	return x509.MarshalPKIXPublicKey(k.k)

```
이런 예시가 있다 이걸로 byte->key, key->byte 될듯?

**Comment by yojkim** [comment]
놀랍게도 `keyUtils.go`에 이미 구현이 되어있네요 ㅋㅋㅋ 

```Go
func PublicKeyToPEM(pub Key) ([]byte, error) {

	if pub == nil {
		return nil, errors.New("Invalid Key")
	}

	switch k := pub.(type) {
	case *rsaPublicKey:

		keyData, err := x509.MarshalPKIXPublicKey(k.pub)
		if err != nil {
			return nil, err
		}

		return pem.EncodeToMemory(
			&pem.Block{
				Type: "RSA PUBLIC KEY",
				Bytes: keyData,
			},
		), nil

	case *ecdsaPublicKey:

		keyData, err := x509.MarshalPKIXPublicKey(k.pub)
		if err != nil {
			return nil, err
		}

		return pem.EncodeToMemory(
			&pem.Block{
				Type: "RSA PUBLIC KEY",
				Bytes: keyData,
			},
		), nil

	default:
		return nil, errors.New("Unspported Public Key Type")
	}

}
```

**Comment by yojkim** [comment]
이걸 저장하고 불러올때만 썼었던거같은데 그냥 전환할때도 사용해도 되는것 같아요.

**Comment by junbeomlee** [comment]
헐 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
오케이 그럼 이름을 바꾸자

**Comment by junbeomlee** [comment]
아 그리고 제안 하나 하자면 
`func PublicKeyToPEM(pub Key) ([]byte, error) {

	if pub == nil {
		return nil, errors.New("Invalid Key")
	}

	switch k := pub.(type) {
	case *rsaPublicKey:

		keyData, err := x509.MarshalPKIXPublicKey(k.pub)
		if err != nil {
			return nil, err
		}

		return pem.EncodeToMemory(
			&pem.Block{
				Type: "RSA PUBLIC KEY",
				Bytes: keyData,
			},
		), nil

	case *ecdsaPublicKey:

		keyData, err := x509.MarshalPKIXPublicKey(k.pub)
		if err != nil {
			return nil, err
		}

		return pem.EncodeToMemory(
			&pem.Block{
				Type: "RSA PUBLIC KEY",
				Bytes: keyData,
			},
		), nil

	default:
		return nil, errors.New("Unspported Public Key Type")
	}

}`

여기서 이렇게 if문으로 처리하는 것보다 Key인터페이스에서 ToPem() []byte라는걸 만들고 그 안에서 
`keyData, err := x509.MarshalPKIXPublicKey(k.pub)
		if err != nil {
			return nil, err
		}

		return pem.EncodeToMemory(
			&pem.Block{
				Type: "RSA PUBLIC KEY",
				Bytes: keyData,
			},
		), nil`
이런식으로 처리하면 if else같은거 다 없애고 그냥 
`func PublicKeyToPEM(pub Key) ([]byte, error) {

	if pub == nil {
		return nil, errors.New("Invalid Key")
	}
        return pub.ToPem()

}`
라는식으로 하게되니까 좋지 if else나 switch는 parameter를 인터페이스(pub Key)로 처리하고
각자 자기(Key)가 처리하는 식으로 하면 더 좋음!!

**Comment by yojkim** [comment]
넵

**Comment by junbeomlee** [comment]
완료
