### ISSUE TITLE
Issue #35에서 제안된 내용 진행중에 다른 이슈가 생겼습니다.

### ISSUE THREAD

**Issue by owljoa** [it-chain/heimdall#40]
헉. 1번 부분은 더 찾아보니 hyperledger에서도 파일명을 SKI로 사용하는군요..! 하하;

2번 부분만 봐주세요!!

그리고 @yojkim 님께 추가적으로 SKI 관련 질문이 있습니다!
제가 생각한 내용과는 다르게 hyperledger 소스를 보니 private key의 SKI함수에서도 결국은 public key를 바이트 형태로 끌어내서 public key의 SKI를 구하는 것을 확인했습니다.
저희 소스에서 ecdsa는 잘되어있는것 같은데 **rsa에서는 public key를 끌어낼때 상수(N:123, E:57)를 사용하게 되어 있는데 이게 어떤 의미가 있는 숫자를 넣으신건가요?**

**2. 특별한 의미가 없는 숫자라면 private key에 내장된 N, E를 사용하는 것으로 수정하려합니다!**

**Comment by yojkim** [comment]
별다른 의미는 없는 것 같네요 ㅋㅋㅋ
