### ISSUE TITLE
private, public key 변수명 모두 대문자 시작으로 바꿔야할듯!!

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/heimdall#6]
키를 사용하고싶은데 사용을 못함.. 인터페이스만 되서..

**Comment by yojkim** [comment]
무슨 말이져??

**Comment by junbeomlee** [comment]
패키지안에서 소문자로 시작하는 변수는 외부에서 접근 불가함!!
예를 들어 rsaPrivatekey 구조체를 쓰고싶은데 못씀 ㅠ

**Comment by junbeomlee** [comment]
Key라는 인터페이스로만 사용가능함

**Comment by yojkim** [comment]
그 구조체에 직접 접근해야하나여??

**Comment by junbeomlee** [comment]
ㅇㅇ 당근!!

**Comment by yojkim** [comment]
근데 알고리즘 상관없이 사용할 수 있게 하는게 목적아니에요?
그래서 Signer 같은 경우도 인터페이스로만 접근 가능하게 했던거아닌가영...??

**Comment by junbeomlee** [comment]
그거랑 퍼블릭으로 푸는거랑은  상관없지!! 그거는 Key라는 인터페이스를 만족하기만 하면 되는거고!!
접근 가능하게 하는거랑은 상관이 없자나

**Comment by yojkim** [comment]
어떤 상황에서 구조체에 직접 접근이 필요한건지 이해가 잘 안가욥

**Comment by junbeomlee** [comment]
내가 그냥 Private key를 가지고 싶은거임!!

**Comment by yojkim** [comment]
그러면 걍 Crypto에 `GetKey()` 이용하면 return 되는데 그걸론 안되나여?? priv, pub 값이 리턴되면 그 나중에 Sign 할때도 RSA인지 ECDSA인지 판단해서 그에 맞는 로직으로 가긴가는데

**Comment by junbeomlee** [comment]
ㄴㄴㄴ 그러면 key인터페이스를 가지는거지
내가 GetKey를 통해서가 아니라 그냥 heimdall에서 정의한 RSAprivateKey구조체를 사용하고싶은데 아예 못사용함

**Comment by junbeomlee** [comment]
RSAprivatekey구조체를 직접 사용해도 어차피 RSAprivatekey는 Key인터페이스를 구현하기 때문에 아무런 문제가없음

**Comment by yojkim** [comment]
ㅋㅋㅋ 넵 수정할게요

**Comment by junbeomlee** [comment]
이해했음?!!!

**Comment by junbeomlee** [comment]
그러니까 거기서 정의한 Key를 기반으로 뭐든지 하고싶은데 추가적으로 뭔가 하려고 해도 Key인터페이스만 줘서 내가 확장을 못함! 그 인터페이스에만 얽혀있다고해야되나

**Comment by yojkim** [comment]
근데 그 바깥에서 뭔가 작업을 처리하게하는 거는 이 라이브러리 구현 쪽에서는 상관 없는거죠? 말이 맞나 ㅋㅋ

**Comment by junbeomlee** [comment]
작업처리를 하게하는 거라는게 무슨말이지?

**Comment by yojkim** [comment]
그 "Key기반으로 뭐든지 하고싶은데" 라고 하신 부분이 반환된 Key를 뭔가 까서 조작하고 싶다는 그런 느낌인가여? 그럴라면 RSAPrivateKey가 필요한거고??

**Comment by junbeomlee** [comment]
ㄴㄴㄴ 조작이라기 보다는 저 구조체를 기준으로 여러곳에서 사용하고 싶은거임!!

**Comment by junbeomlee** [comment]
뭐랄까 표준이랄까?

**Comment by yojkim** [comment]
기준이라는건 Key를 의미하나영??

**Comment by yojkim** [comment]
Key 인터페이스만 맞추고 RSAPrivateKey든 ECDSAPrivateKey든 구조체 맞춰서 사용만 하고싶다?!~

**Comment by junbeomlee** [comment]
아니아니그게아니라

**Comment by junbeomlee** [comment]
그 구조체 자체가 기준인거지 그러니까 key라는게 사실 여러개 있자나 구현체가 너가만든 RSA가 아니더라도 다른 라이브러리들에서도 RSA키들을 제공해주는데 우리 프로젝트에서는 다 heimdall을 기준으로 하고싶은거지

**Comment by yojkim** [comment]
아 그러면 이게 맞나여?? 예를 들어서 다른 곳에서 다른 형식의 RSA Key가 오더라도 heimdall에서 만든 RSA 구조체에 맞춰서 Key로 사용가능?!!?!?!??!

**Comment by junbeomlee** [comment]
ㅇㅇ 그런느낌?!! ㅇㅇ 우리는 저 구조체를 기준으로 다 하고싶은거지 키에 대해서는!!

**Comment by yojkim** [comment]
오우 이해댐여 very good description

**Comment by junbeomlee** [comment]
여기서 만든 Key 인터페이스는 signer ,verifier같은 이런애들이 pri,pub이나 rsa,ecdsa에 상관없이 동일하게 처리하기 위함이고 그거는 그거대로 가는거고 구조체 자체로도 우리는 기준으로 해서 이용하고싶다 이런거
굳굳

**Comment by yojkim** [comment]
그럼 그거 생각해서 만들어볼게욥

**Comment by junbeomlee** [comment]
오키오키!! 굳굳 아주 천재구만..

**Comment by junbeomlee** [comment]
완료
